version: "3.6"
services:
  mariadb:
    image: "mariadb"
#    platform: linux/amd64
    container_name: app_mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: toy
    expose:
      - "3306"

  backend:
#    platform: linux/amd64
    container_name: app_backend
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app

