# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto Deployment to DockerHub & AWS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./backend
    
    strategy:
        matrix:
          node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: npm ci & build
      run: |
        npm ci
        npm run build --if-present
      working-directory: ${{env.working-directory}}

    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
    - name: build and release to DockerHub
      env:
        NAME: brinst07
        REPO: github_action_test
      run: |
        docker build -t $REPO .
        docker tag $REPO:latest $NAME/$REPO:latest
        docker push $NAME/$REPO:latest
      working-directory: ${{env.working-directory}}  
        
